### PR TITLE
Module Version 3.0 Rewrite

### LINKED ISSUE #31: Support deleting of presents
https://eww.pass.panasonic.co.jp/pro-av/support/content/guide/DEF/HE50_120_IP/HDIntegratedCamera_InterfaceSpecifications-E.pdf

Page 21, Table 3.1.7
send string #C{present # -1}

Would be nice if the user could specify a range of presets to delete but that would be more work vs just having to program many actions on 1 button.

### LINKED ISSUE #50: Add white balance adjustment and a preset button which doenst save PTZ position
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Hi everyone, is it possible to include a control for the White Balance settings for panasonic PTZ cameras? Or to exclude the PTZ-position when saving a preset? Best regards!

### Usecases

When using the Panasonic PTZ camera starting at day and going into night it might be handy to change the white balance with one button for multiple cameras at once. This could also be solved by using a preset which doesnt include the PTZ position.

### LINKED ISSUE #54: Feedback FOCUS not working
Return always Auto feedback.

Bitfocus companion v3.0.0

### LINKED ISSUE #56: How to send custom commands ?
Hello there and thank you for your work!

I'm planning to acquire the new Streamdeck+ and would like to use it as a Remote Operation Panel.

I'm interested in controlling camera settings such as temperature, matrix, gain, etc. with just a touch of a button.

I understand that it might be challenging to include all commands as presets in Companion, but would it be possible to implement a "custom command" button that sends the code I find on this website to my cameras?

https://eww.pass.panasonic.co.jp/pro-av/support/content/guide/EN/top.html

I know that I can send the command using generic HTTP requests, but I believe this method would be more cumbersome in my opinion.

### LINKED ISSUE #57: Variable functionality for module
Feature request for Panasonic PTZ module

I'm working on a project involving multiple Panasonic PTZ cameras and large numbers of presets for each camera.

I would like to be able to use companion custom variables for PTZ save/recall operations.

Currently I have to create many pages of recall/save buttons for each camera's presets.

Any update to the functionality of these buttons requires extensive/time 

I could probably make something work with the Generic TCP/UDP module but that seems not the best way

Thanks, Jim

### LINKED ISSUE #61: feature request: turn on/off the color bars
Would love to have the option to turn on color bars on and off from the system settings

### LINKED ISSUE #67: Autotracking functionality
Hi, 

The Panasonic UE40,50 and 80 have just had autotracking added. This has been added to the AW protocol. Would it be possible to add to the Companion module? 

Sam

### LINKED ISSUE #77: Exposure - Iris Mode (Auto Iris)
Exposure - Iris Mode (Auto Iris) - auto and manual settings seem to be the wrong way round! Controlling UE-160 using the UE-150 profile (UE-160 isn't there yet)

### PR DESCRIPTION
**Pull request by premultiply**
THIS IS STILL WORK IN PROGRESS

sdplus

- Complete rewrite of the module with initial focus on full support for modern non-PTZ cameras
- Added support for UE80/UE50/UE40 series
- Added support for CX350/4000 series
- Added support for UE100/UR100
- Added support for UE20/HE20
- Added and fixed support for many other camera models by walking through lots of specs in detail
- Added Color bar control [replaces #79, fixes #61]
- Added on-camera Autotracking features (on recent camera models like UE50) [fixes #67]
- Added preset thumbnail as button background by feedback
- Added preset selected and completed status feedback
- Added preset memory save and clear actions [fixes #31]
- Added nice multi-action preset memory recall/memorize/clear button presets
- Added support for rotary control actions where applicable
- Added instant command return code feedback
- Added Streaming control actions and feedbacks for SRT Caller, RTMP Client and MPEG-TS Output modes
- Added Recording control actions and feedbacks incl. SD card slot usage
- Added Custom command [fixes #56]
- Fixed many protocol glitches and model specific data layouts
- Completly refactored and fixed camera model properties
- Added common color correction actions und variables (gain, pedestal, white balance, color temperature, ...) [replaces #80] [fixes #50]
- Added all feedbacks for operational states
- Unified button actions for set/toggle/up/down where applicable
- Added polling of data from camera which is not included in push events
- Added inital explicit data pull from camera where bulk retrieval is not available or does report wrong data
- Added decoding of error codes
- Big rewrite of presets to hopefully better fit common production needs and allow them to change easily
- Added graphical focus/zoom/iris position bar and numeric absolute and relative position
- Added iris F-value decode on supported models
- Added absolute pan/tilt position (angle)
- Fixed firmware version retrieval
- Added camera title
- Fixed connection handling and reconnect behavior
- Added config switch and delay setting for polling
- Added Image Stabilization (O.I.S.)
- Added Night Mode

...and many more things that I stumbled upon but can't remember in detail ;)

Attention:
Since this is more or less a complete rewrite of this module with clean-ups, refactoring and
is also an attempt to achieve simplification of names, variables, actions, feedback, etc., there is unfortunately no upgrade script (yet?) for automatically updating or migrating existing companion configurations.
In most cases, you will therefore have to start from scratch with your companion configuration for functions of this module. I'm very sorry, but the changes (and improvements) are too large to be migrated automatically with reasonable effort. But I also have to admit that I still don't understand enough how upgrade scripts work. Maybe someone can support me?

Testing by myself on HR140, UE50, UE150, UE100, HE40, CX350

Open things that still need to be done and others that are being worked on:
- [ ] Upgrade, improve, clean and fix all Presets
- [ ] Check and fix Preset buttons with two variables
- [ ] Double check all camera model properties and variables, action, feedback conditions
- [ ] Testing, testing, testing

Replaces #80 #79 #76
Fixes #77 #67 #61 #56 #50 #36 #31
Should fix #54 #64 #14
May fix #57 #53 #43 #41
Requires https://github.com/bitfocus/companion/issues/2837

### CODE REVIEW

**Comment by josephdadams** [comment]
@premultiply as this module is used quite extensively by many,  make sure you write an upgrade script that converts any renamed actions, feedbacks, variables, etc. to fit your new format. We will not be able to incorporate your work until then. Thanks!

**Comment by premultiply** [comment]
Since this is more or less a complete rewrite of this module with clean-ups, refactoring and is also an attempt to achieve simplification of names, variables, actions, feedback, etc., there is unfortunately no upgrade script for automatically updating or migrating existing companion configurations. Many things have changed (and fixed) how they work internally so I do not see a good way to migrate them yet.
In most cases, you will therefore have to start from scratch with your configuration regarding this module. I'm very sorry, but the changes (and improvements) are too large to be migrated automatically with reasonable effort. But I also have to admit that I still don't understand enough how upgrade scripts work. Maybe someone can support me?

Maybe it would be even better to add it as new module and keep the current version for legacy reasons?

**Comment by Julusian** [comment]
If you want to look at some upgrade scripts, the atem module has a bunch at varying complexity https://github.com/bitfocus/companion-module-bmd-atem/blob/main/src/upgrades.ts
I'm not aware of anywhere that has had to handle a breaking refactor of this scale though. There isn't currently a way to do anything for usages of variables either.

Tbh, unless there are upgrade scripts that handle a majority of things, then I would prefer to add this as a new module. There are 700-1000 users of the module each day, working out to about 2000 unique users within a period of a month. That is something like 3-5% of the users of Companion, and last I checked this was in the top 20 most used modules.

So that is a lot of users who will not enjoy the upgrade to the version which includes this, if it isn't done as a new module or with sufficient upgrade scripts.
Maybe we can do something in the ui connections list to nudge users to switch to the new module. And there is other future work being thought about which could help mitigate this without needing to create a new module, but that won't be ready for 3.3

**Comment by premultiply** [comment]
@Julusian What do you think about creating this upgrade as new module `companion-module-panasonic-camera` (fits better to the supported models including non-PTZ cameras) and depreciating this `companion-module-panasonic-ptz` module.

**Comment by Julusian** [comment]
@premultiply yes, I think that is the best way forward. I've created a new repository and sent you an invite to it https://github.com/bitfocus/companion-module-panasonic-cameras
Push your code there, then once it is included in the betas we can look at how best to label this repository/module as deprecated and what we can do to gently encourage users to migrate across.
I don't want to keep this repository around for now, so that bugfixes can still be made for the old module.

**Comment by premultiply** [comment]
Thx @Julusian

Will be left here for reference.
Further work will be continued at https://github.com/bitfocus/companion-module-panasonic-cameras/

**Comment by cyprient** [comment]
@Julusian I will continue to maintain this module as it is used a lot on Companion, and big Companion configurations may be hard and time consuming to move to a new module.

**Comment by premultiply** [comment]
Replaced by https://github.com/bitfocus/companion-module-panasonic-cameras/releases/tag/v1.0.0

**Pull request closed without merging**
